
chunk_size: 4096
retries: 4

spacy_model: en_core_web_sm

## must manually install other models
# spacy_model: en_core_web_md
# spacy_model: en_core_web_lg

csv: yes

output_file: clinical_data.txt


search_terms:
  - reproduction number
  - reproduction rate
  - incubation time
  # - covid
  - asymptomatic
  - Ro


variable_patterns:
  - id: reproduction+number
    pattern_matchers:
      - - LOWER: reproduction
        - LOWER: number
        - LIKE_NUM: yes
      - - LOWER: reproduction
        - LOWER: number
        - {}
        - LIKE_NUM: yes

  - id: reproduction+rate
    pattern_matchers:
      - - LOWER: reproduction
        - LOWER: rate
        - LIKE_NUM: yes
      - - LOWER: reproduction
        - LOWER: rate
        - {}
        - LIKE_NUM: yes

  - id: incubation+time
    pattern_matchers:
      - - LOWER: incubation
        - LOWER: time
        - LIKE_NUM: yes
      - - LIKE_NUM: yes
        - LOWER: incubation
        - LOWER: time
      - - LIKE_NUM: yes
        - {}
        - LOWER: incubation
        - LOWER: time
      - - LOWER: incubation
        - LOWER: time
        - {}
        - LIKE_NUM: yes
      - - LOWER: incubation
        - LOWER: time
        - {}
        - LIKE_NUM: yes
        - {}

  # - id: asymptomatic
  #   pattern_matchers:
  #     - - LOWER: asymptomatic

disease_patterns:
  - id: covid
    pattern_matchers:
      - - LOWER: covid-19
      - - LOWER: covid
        - LOWER: 19
      - - LOWER: covid
        - {}
        - LOWER: 19
      - - LOWER: sars
        - {}
        - LOWER: cov
  - id: flu
    pattern_matchers:
      - - LOWER: flu

